apiVersion: v1
kind: Service
metadata:
  name: dockerapp-svc
  labels:
    app: springbbot
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: springbbot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerapp
  labels:
    app: springbbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbbot
  template:
    metadata:
      labels:
        app: springbbot
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
