name: <+stage.name>
replicas: 1
service: svc

image: <+artifact.image>
# dockercfg: <+artifact.imagePullSecret>

# createNamespace: true
# namespace: <+infra.namespace>

serviceType: LoadBalancer
servicePort: 8080
serviceTargetPort: 8080

env:
  config:
    key1: value10
  secrets:
    key2: value2
