apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  selector:
    matchLabels:
      app: springboot
  replicas: {{.Values.replicas}}
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
		imagePullPolicy: Always
        ports:
        - containerPort: 80
